const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE||'/Users/dcor/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const base=process.argv[2]||'http://127.0.0.1:8109',out=process.env.REPORT_DIR||'../reports';fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/#country=FRA&mode=balance');await page.waitForFunction(()=>window.oilAtlas);
 async function menu(){if(!(await page.locator('#map-settings').isVisible()))await page.locator('#filters-toggle').click();}
 const info=await page.evaluate(()=>({canary:oilAtlas.graph.canary,count:oilAtlas.graph.flows.length,countries:oilAtlas.data.countries.length,state:oilAtlas.state}));
 if(process.env.EXPECT_CANARY)assert.equal(info.canary,process.env.EXPECT_CANARY==='1');
 if(process.env.EXPECT_FLOWS)assert.equal(info.count,+process.env.EXPECT_FLOWS);
 assert.equal(info.countries,215);assert.equal(info.state.mode,'trade');
 assert.equal(await page.locator('.country-name').innerText(),'Франция');
 assert.equal((await page.locator('[data-stat="consumption"]').innerText()).replace(/\s/g,''),'1352');
 assert.equal((await page.locator('[data-stat="production"]').innerText()).replace(/\s/g,''),'10');
 assert.equal((await page.locator('[data-stat="balance"]').innerText()).replace(/\s/g,''),'1342');
 assert.equal(await page.locator('table').count(),0);
 assert.ok(await page.locator('.country').count()>170);
 const bounds=await page.locator('#world-map').boundingBox();assert.equal(bounds.width,1440);assert.equal(bounds.height,900);
 await page.locator('[data-partner="DZA"]').click();assert.ok((await page.locator('#popup-content').innerText()).includes('Алжир → Франция'));assert.ok((await page.locator('#popup-content').innerText()).includes('4,3'));await page.locator('#close-popup').click();
 await page.locator('[data-partner="USA"]').click();assert.ok((await page.locator('#popup-content').innerText()).includes('10,1'));await page.locator('#close-popup').click();
 for(const f of await page.evaluate(()=>oilAtlas.visibleFlows))assert.equal(f.destination,'FRA');
 await page.screenshot({path:out+'/v2-france.png'});
 async function select(code){if(!(await page.locator('.search').isVisible()))await page.locator('#search-toggle').click();await page.locator('#country-search').fill(code);await page.locator(`[data-country="${code}"]`).click();assert.equal(await page.evaluate(()=>oilAtlas.state.country),code);}
 await select('USA');assert.ok(await page.locator('[data-partner="VEN"]').count());
 await page.locator('[data-partner="VEN"]').click();assert.ok((await page.locator('#popup-content').innerText()).includes('Венесуэла → США'));assert.ok((await page.locator('#popup-content').innerText()).includes('139,8'));await page.locator('#close-popup').click();
 await page.locator('[data-direction="exports"]').click();await page.locator('#all-flows').click({force:true});assert.ok(await page.locator('[data-partner="CHN"]').count());
 await menu();await page.locator('[data-product="gasoline"]').click();assert.equal((await page.locator('[data-stat="consumption"]').innerText()).replace(/\s/g,''),'8935');await page.locator('[data-partner="MEX"]').click();assert.ok((await page.locator('#popup-content').innerText()).toLowerCase().includes('автомобильный бензин'));await page.locator('#close-popup').click();
 await menu();await page.locator('[data-product="diesel"]').click();assert.ok(await page.locator('[data-partner="MEX"]').count());
 await menu();await page.locator('[data-product="pipeline"]').click();await page.locator('[data-direction="both"]').click();
 const pipes=await page.evaluate(()=>oilAtlas.visibleFlows);assert.equal(pipes.length,4);assert.ok(pipes.find(f=>f.origin==='CAN'&&f.destination==='USA').value>87);assert.ok(pipes.find(f=>f.origin==='USA'&&f.destination==='MEX').value>66);assert.ok(pipes.find(f=>f.origin==='MEX'&&f.destination==='USA').value<.01);
 await page.reload();await page.waitForFunction(()=>window.oilAtlas);assert.equal(await page.evaluate(()=>oilAtlas.state.product),'pipeline');assert.equal(await page.evaluate(()=>oilAtlas.state.direction),'both');
 await page.screenshot({path:out+'/v2-us-pipeline.png'});
 await menu();await page.locator('[data-product="lng"]').click();await page.locator('[data-direction="exports"]').click();await page.locator('#all-flows').click({force:true});assert.ok(await page.locator('[data-partner="FRA"]').count());
 await page.locator('#sites-button').click();assert.ok(await page.locator('[data-site="permian"]').count());assert.ok(await page.locator('[data-site="sabine"]').count());assert.equal(await page.locator('.state').count(),56);
 await page.locator('[data-site="permian"]').click();assert.ok((await page.locator('#popup-content').innerText()).includes('6.6'));await page.locator('#close-popup').click();
 await page.locator('[data-state="Texas"]').press('Enter');assert.ok((await page.locator('#popup-content').innerText()).replace(/\s/g,'').includes('5760,6'));await page.locator('#close-popup').click();await page.screenshot({path:out+'/v2-us-sites.png'});await page.reload();await page.waitForFunction(()=>window.oilAtlas);assert.equal(await page.evaluate(()=>oilAtlas.state.sites),true);assert.ok(await page.locator('[data-site="sabine"]').count());
 await select('FRA');await menu();await page.locator('[data-product="pipeline"]').click();assert.equal(await page.locator('.partner-label').count(),0);assert.ok((await page.locator('#coverage-note').innerText()).includes('Нет национальной'));await page.locator('#sites-button').click();assert.ok(await page.locator('[data-site="dunkerque"]').count());
 await select('JPN');await menu();await page.locator('#map-mode').selectOption('reserves');assert.equal(await page.locator('.country[data-iso="JPN"]').getAttribute('fill'),'#263a46');
 await select('LUX');await menu();await page.locator('[data-product="crude"]').click();assert.equal((await page.locator('[data-stat="production"]').innerText()).replace(/\s/g,''),'0');
 await menu();await page.locator('#map-mode').selectOption('balance');assert.equal(await page.evaluate(()=>oilAtlas.state.mode),'balance');await page.reload();await page.waitForFunction(()=>window.oilAtlas);assert.equal(await page.evaluate(()=>oilAtlas.state.mode),'balance');
 await select('FRA');await menu();await page.locator('[data-product="lng"]').click();await page.locator('[data-direction="imports"]').click();
 await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForFunction(()=>window.oilAtlas);await page.waitForTimeout(300);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight),844);
 await page.locator('[data-partner="USA"]').click();assert.ok((await page.locator('#popup-content').innerText()).includes('14,3'));await page.locator('#close-popup').click();await page.screenshot({path:out+'/v2-mobile.png'});
 await menu();await page.locator('#about-button').click();assert.ok(await page.locator('#about').isVisible());await page.locator('#close-about').click();
 assert.deepEqual(errors,[]);fs.writeFileSync(out+'/v2-smoke-result.json',JSON.stringify({status:'PASS',base,...info,variants:['France crude positive demand','country-only selected edges','US crude Venezuela China','gasoline','distillates','gas pipeline bidirectional','LNG','US basin and terminal drilldown','state boundaries','unknown vs zero','hash resume including sites','mobile full viewport','sources dialog'],errors},null,2));
 await browser.close();console.log('PASS',JSON.stringify(info));
})().catch(e=>{console.error(e);process.exit(1)});
